export const metadata = {
  title: 'Desafio azapfy',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="pt-br">
      <body style={{backgroundColor: 'gray'}}>{children}</body>
    </html>
  )
}
